# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_mcmc_BBS_Free <- function(ydata, vdata, vtv, ptp, fxdata, phixgrid, phixdata, kall, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, beta, theta, tau2, tau, sigma2, sigma) {
    .Call(`_HBSARSCdev_get_mcmc_BBS_Free`, ydata, vdata, vtv, ptp, fxdata, phixgrid, phixdata, kall, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, beta, theta, tau2, tau, sigma2, sigma)
}

get_mcmc_2DBSAR_Free <- function(ydata, vdata, vtv, ptp, fxdata, phixgrid, phixdata, wk, egamkall, freq_sum, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, beta, theta, gampar, tau2, tau, sigma2, sigma) {
    .Call(`_HBSARSCdev_get_mcmc_2DBSAR_Free`, ydata, vdata, vtv, ptp, fxdata, phixgrid, phixdata, wk, egamkall, freq_sum, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, beta, theta, gampar, tau2, tau, sigma2, sigma)
}

get_mcmc_2DBSAR_Mono <- function(ydata, vdata, vtv, iflagMainpn, xinxMain, xinx, xoverMain, xover, xdelta, xrange, fxdata, fxMaindata, fx12data, fx12grid_mat, fxMain_mat, f12apx_weights, phixgrid, phiMain, wk, wkMain, egamkallMain, egamkall, freq_sum, kall0, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, met_para, beta, thetaMain, theta, xiparMain, xipar, gamMain, gampar, tau2Main, tau2, sigma2, sigma) {
    .Call(`_HBSARSCdev_get_mcmc_2DBSAR_Mono`, ydata, vdata, vtv, iflagMainpn, xinxMain, xinx, xoverMain, xover, xdelta, xrange, fxdata, fxMaindata, fx12data, fx12grid_mat, fxMain_mat, f12apx_weights, phixgrid, phiMain, wk, wkMain, egamkallMain, egamkall, freq_sum, kall0, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, met_para, beta, thetaMain, theta, xiparMain, xipar, gamMain, gampar, tau2Main, tau2, sigma2, sigma)
}

get_mcmc_BSAR_Free <- function(ydata, vdata, vtv, ptp, fxdata, phixgrid, phixdata, wk, egamkall, kall, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, beta, theta, gampar, tau2, tau, sigma2, sigma) {
    .Call(`_HBSARSCdev_get_mcmc_BSAR_Free`, ydata, vdata, vtv, ptp, fxdata, phixgrid, phixdata, wk, egamkall, kall, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, beta, theta, gampar, tau2, tau, sigma2, sigma)
}

get_mcmc_HBBS <- function(data_all, dpara, xgrid, xinx, xover, nobs, iptHB1, ztz, vtv, wtw, phi2, cpara, ace_para, probit_para, ordinal_para, tau_para, eta_para, met_para, squish_para1, squish_para2, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, slope_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, xiparall, tau2all, tauall, sigma2, sigma, betallg, rhoallg, thetallg, zetag, omegag, zeta0g, omega0g, psiallg, psi0g, mslope_logg, mslope0_logg, mslopeg, mslope0g, mslope_log_sigmag, fxgridallg, f0xgridg) {
    .Call(`_HBSARSCdev_get_mcmc_HBBS`, data_all, dpara, xgrid, xinx, xover, nobs, iptHB1, ztz, vtv, wtw, phi2, cpara, ace_para, probit_para, ordinal_para, tau_para, eta_para, met_para, squish_para1, squish_para2, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, slope_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, xiparall, tau2all, tauall, sigma2, sigma, betallg, rhoallg, thetallg, zetag, omegag, zeta0g, omega0g, psiallg, psi0g, mslope_logg, mslope0_logg, mslopeg, mslope0g, mslope_log_sigmag, fxgridallg, f0xgridg)
}

get_mcmc_2DHBSAR <- function(data_all, nobs, iptHB1, ztz, vtv, wtw, phi2, cpara, gamma_para, tau_para, eta_para, met_para, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, gammall, tau2all, tauall, sigma2, sigma, betallg, thetallg) {
    .Call(`_HBSARSCdev_get_mcmc_2DHBSAR`, data_all, nobs, iptHB1, ztz, vtv, wtw, phi2, cpara, gamma_para, tau_para, eta_para, met_para, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, gammall, tau2all, tauall, sigma2, sigma, betallg, thetallg)
}

get_mcmc_HBSAR <- function(data_all, dpara, xgrid, xinx, xover, nobs, iptHB1, ztz, vtv, wtw, phi2, cpara, ace_para, probit_para, ordinal_para, gamma_para, tau_para, eta_para, met_para, squish_para1, squish_para2, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, slope_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, xiparall, gammall, tau2all, tauall, sigma2, sigma, betallg, rhoallg, thetallg, zetag, omegag, zeta0g, omega0g, psiallg, psi0g, mslope_logg, mslope0_logg, mslopeg, mslope0g, mslope_log_sigmag, fxgridallg, f0xgridg) {
    .Call(`_HBSARSCdev_get_mcmc_HBSAR`, data_all, dpara, xgrid, xinx, xover, nobs, iptHB1, ztz, vtv, wtw, phi2, cpara, ace_para, probit_para, ordinal_para, gamma_para, tau_para, eta_para, met_para, squish_para1, squish_para2, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, slope_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, xiparall, gammall, tau2all, tauall, sigma2, sigma, betallg, rhoallg, thetallg, zetag, omegag, zeta0g, omega0g, psiallg, psi0g, mslope_logg, mslope0_logg, mslopeg, mslope0g, mslope_log_sigmag, fxgridallg, f0xgridg)
}

rcpp_CumTrap <- function(f, delta) {
    .Call(`_HBSARSCdev_rcpp_CumTrap`, f, delta)
}

rcpp_trapint <- function(f, xdelta) {
    .Call(`_HBSARSCdev_rcpp_trapint`, f, xdelta)
}

rcpp_Int2D <- function(fmat, xdelta) {
    .Call(`_HBSARSCdev_rcpp_Int2D`, fmat, xdelta)
}

rcpp_CumInt2D <- function(fmat, xdelta) {
    .Call(`_HBSARSCdev_rcpp_CumInt2D`, fmat, xdelta)
}

get_ex_idx <- function(len, idx) {
    .Call(`_HBSARSCdev_get_ex_idx`, len, idx)
}

get_seq <- function(a, b) {
    .Call(`_HBSARSCdev_get_seq`, a, b)
}

rcpp_rndtna <- function(mu, sigma, xtop) {
    .Call(`_HBSARSCdev_rcpp_rndtna`, mu, sigma, xtop)
}

rcpp_rndtna2 <- function(mu, sigma, xtop) {
    .Call(`_HBSARSCdev_rcpp_rndtna2`, mu, sigma, xtop)
}

rcpp_rndtnb <- function(mu, sigma, xbot) {
    .Call(`_HBSARSCdev_rcpp_rndtnb`, mu, sigma, xbot)
}

rcpp_rndtnb2 <- function(mu, sigma, xbot) {
    .Call(`_HBSARSCdev_rcpp_rndtnb2`, mu, sigma, xbot)
}

rcpp_rndtnab <- function(mu, sigma, xbot, xtop) {
    .Call(`_HBSARSCdev_rcpp_rndtnab`, mu, sigma, xbot, xtop)
}

rcpp_GetSquish <- function(omega, psi, xgrid) {
    .Call(`_HBSARSCdev_rcpp_GetSquish`, omega, psi, xgrid)
}

rcpp_GetMonofxgrid <- function(fpars) {
    .Call(`_HBSARSCdev_rcpp_GetMonofxgrid`, fpars)
}

rcpp_GetMonoSamefxgrid <- function(fpars) {
    .Call(`_HBSARSCdev_rcpp_GetMonoSamefxgrid`, fpars)
}

rcpp_GetMonoDiffxgrid <- function(fpars) {
    .Call(`_HBSARSCdev_rcpp_GetMonoDiffxgrid`, fpars)
}

rcpp_GetSfxgrid <- function(fpars, d3) {
    .Call(`_HBSARSCdev_rcpp_GetSfxgrid`, fpars, d3)
}

rcpp_GetUseg <- function(x, gz, omega, xdelta) {
    .Call(`_HBSARSCdev_rcpp_GetUseg`, x, gz, omega, xdelta)
}

rcpp_GetMMfxgrid <- function(fpars) {
    .Call(`_HBSARSCdev_rcpp_GetMMfxgrid`, fpars)
}

rcpp_GetUfxgrid <- function(fpars) {
    .Call(`_HBSARSCdev_rcpp_GetUfxgrid`, fpars)
}

rcpp_Getfx <- function(fpars) {
    .Call(`_HBSARSCdev_rcpp_Getfx`, fpars)
}

rcpp_GetSCfxobs <- function(xinx, xover, fxgrid) {
    .Call(`_HBSARSCdev_rcpp_GetSCfxobs`, xinx, xover, fxgrid)
}

rcpp_cholSol <- function(b, U) {
    .Call(`_HBSARSCdev_rcpp_cholSol`, b, U)
}

GetMetVec <- function(w, m0, alpha, ndim) {
    .Call(`_HBSARSCdev_GetMetVec`, w, m0, alpha, ndim)
}

SetMetVec <- function(Met, w, m0, alpha, ndim) {
    invisible(.Call(`_HBSARSCdev_SetMetVec`, Met, w, m0, alpha, ndim))
}

AdaptMetVar <- function(x) {
    .Call(`_HBSARSCdev_AdaptMetVar`, x)
}

AdaptMetUpdate <- function(x) {
    invisible(.Call(`_HBSARSCdev_AdaptMetUpdate`, x))
}

AdaptMetUpdate2 <- function(x) {
    .Call(`_HBSARSCdev_AdaptMetUpdate2`, x)
}

UpdateMet <- function(x, nb, fct) {
    invisible(.Call(`_HBSARSCdev_UpdateMet`, x, nb, fct))
}

UpdateMet2 <- function(x, nb, fct) {
    .Call(`_HBSARSCdev_UpdateMet2`, x, nb, fct)
}

rcpp_getsmooth <- function(tau2, gampar, egamkall, theta2, wk, tau2_s0, tau2_rn, freq_sum) {
    .Call(`_HBSARSCdev_rcpp_getsmooth`, tau2, gampar, egamkall, theta2, wk, tau2_s0, tau2_rn, freq_sum)
}

rcpp_getsmoothSC <- function(tau2, gampar, theta, theta2, freqs, egamkall, wk, tau2_s0, tau2_rn, bflagZ) {
    .Call(`_HBSARSCdev_rcpp_getsmoothSC`, tau2, gampar, theta, theta2, freqs, egamkall, wk, tau2_s0, tau2_rn, bflagZ)
}

rcpp_fdata_apx <- function(fmat, f12apx_weights, xinx, xover, nint) {
    .Call(`_HBSARSCdev_rcpp_fdata_apx`, fmat, f12apx_weights, xinx, xover, nint)
}

rcpp_get_phixgrid_2D <- function(phixgrid, xgrid, xrange, xmin, freq_all, phix0, phiy0, ntheta, nint) {
    invisible(.Call(`_HBSARSCdev_rcpp_get_phixgrid_2D`, phixgrid, xgrid, xrange, xmin, freq_all, phix0, phiy0, ntheta, nint))
}

GetSmoothGamma <- function(gampar, theta, theta0, tau2, gamma_alpha, gamma_beta, wk, kall, gmax) {
    .Call(`_HBSARSCdev_GetSmoothGamma`, gampar, theta, theta0, tau2, gamma_alpha, gamma_beta, wk, kall, gmax)
}

GetGammaHyper <- function(gamma_alpha, gamma_beta, gamma_mu, gamma_sigma, gamma_sigma2, gammall, theta0, eta02, gamma_sum, lgamma_sum, kall, gamma_met, mu_bot, mu_top, sigma_bot, sigma_top, gamma_mu_m0, gamma_mu_v02, gamma_sigma_m0, gamma_sigma_v02, ingroup, freq_sum, gmax) {
    .Call(`_HBSARSCdev_GetGammaHyper`, gamma_alpha, gamma_beta, gamma_mu, gamma_sigma, gamma_sigma2, gammall, theta0, eta02, gamma_sum, lgamma_sum, kall, gamma_met, mu_bot, mu_top, sigma_bot, sigma_top, gamma_mu_m0, gamma_mu_v02, gamma_sigma_m0, gamma_sigma_v02, ingroup, freq_sum, gmax)
}

rcpp_GetMainfxdata <- function(xinx, xover, fxgrid) {
    .Call(`_HBSARSCdev_rcpp_GetMainfxdata`, xinx, xover, fxgrid)
}

get_phixgrid2D <- function(xgrid, phix0, phiy0, freq_all, xmin, xrange, ntheta, nint) {
    .Call(`_HBSARSCdev_get_phixgrid2D`, xgrid, phix0, phiy0, freq_all, xmin, xrange, ntheta, nint)
}

