// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// get_mcmc_BBS_Free
Rcpp::List get_mcmc_BBS_Free(arma::colvec& ydata, arma::mat& vdata, arma::mat& vtv, arma::mat& ptp, arma::colvec& fxdata, arma::mat& phixgrid, arma::mat& phixdata, arma::colvec& kall, double tau2_s0, double tau2_rn, double sigma2_s0, double sigma2_rn, arma::mat& beta_v0i, arma::colvec& beta_v0im0, arma::vec& cpara, arma::colvec& beta, arma::mat& theta, double tau2, double tau, double sigma2, double sigma);
RcppExport SEXP _HBSARSCdev_get_mcmc_BBS_Free(SEXP ydataSEXP, SEXP vdataSEXP, SEXP vtvSEXP, SEXP ptpSEXP, SEXP fxdataSEXP, SEXP phixgridSEXP, SEXP phixdataSEXP, SEXP kallSEXP, SEXP tau2_s0SEXP, SEXP tau2_rnSEXP, SEXP sigma2_s0SEXP, SEXP sigma2_rnSEXP, SEXP beta_v0iSEXP, SEXP beta_v0im0SEXP, SEXP cparaSEXP, SEXP betaSEXP, SEXP thetaSEXP, SEXP tau2SEXP, SEXP tauSEXP, SEXP sigma2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type ydata(ydataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type vdata(vdataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type vtv(vtvSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ptp(ptpSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type fxdata(fxdataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phixgrid(phixgridSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phixdata(phixdataSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type kall(kallSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_s0(tau2_s0SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_rn(tau2_rnSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_s0(sigma2_s0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_rn(sigma2_rnSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta_v0i(beta_v0iSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type beta_v0im0(beta_v0im0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type cpara(cparaSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mcmc_BBS_Free(ydata, vdata, vtv, ptp, fxdata, phixgrid, phixdata, kall, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, beta, theta, tau2, tau, sigma2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// get_mcmc_2DBSAR_Free
Rcpp::List get_mcmc_2DBSAR_Free(arma::colvec& ydata, arma::mat& vdata, arma::mat& vtv, arma::mat& ptp, arma::colvec& fxdata, arma::mat& phixgrid, arma::mat& phixdata, double wk, arma::colvec& egamkall, arma::colvec& freq_sum, double tau2_s0, double tau2_rn, double sigma2_s0, double sigma2_rn, arma::mat& beta_v0i, arma::colvec& beta_v0im0, arma::vec& cpara, arma::colvec& beta, arma::mat& theta, double gampar, double tau2, double tau, double sigma2, double sigma);
RcppExport SEXP _HBSARSCdev_get_mcmc_2DBSAR_Free(SEXP ydataSEXP, SEXP vdataSEXP, SEXP vtvSEXP, SEXP ptpSEXP, SEXP fxdataSEXP, SEXP phixgridSEXP, SEXP phixdataSEXP, SEXP wkSEXP, SEXP egamkallSEXP, SEXP freq_sumSEXP, SEXP tau2_s0SEXP, SEXP tau2_rnSEXP, SEXP sigma2_s0SEXP, SEXP sigma2_rnSEXP, SEXP beta_v0iSEXP, SEXP beta_v0im0SEXP, SEXP cparaSEXP, SEXP betaSEXP, SEXP thetaSEXP, SEXP gamparSEXP, SEXP tau2SEXP, SEXP tauSEXP, SEXP sigma2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type ydata(ydataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type vdata(vdataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type vtv(vtvSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ptp(ptpSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type fxdata(fxdataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phixgrid(phixgridSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phixdata(phixdataSEXP);
    Rcpp::traits::input_parameter< double >::type wk(wkSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type egamkall(egamkallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type freq_sum(freq_sumSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_s0(tau2_s0SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_rn(tau2_rnSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_s0(sigma2_s0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_rn(sigma2_rnSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta_v0i(beta_v0iSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type beta_v0im0(beta_v0im0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type cpara(cparaSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type gampar(gamparSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mcmc_2DBSAR_Free(ydata, vdata, vtv, ptp, fxdata, phixgrid, phixdata, wk, egamkall, freq_sum, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, beta, theta, gampar, tau2, tau, sigma2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// get_mcmc_2DBSAR_Mono
Rcpp::List get_mcmc_2DBSAR_Mono(arma::colvec& ydata, arma::mat& vdata, arma::mat& vtv, arma::vec& iflagMainpn, arma::ucube& xinxMain, arma::umat& xinx, arma::mat& xoverMain, arma::vec& xover, arma::vec& xdelta, arma::vec& xrange, arma::colvec& fxdata, arma::mat& fxMaindata, arma::colvec& fx12data, arma::mat& fx12grid_mat, arma::cube& fxMain_mat, arma::mat& f12apx_weights, arma::mat& phixgrid, arma::cube& phiMain, double wk, double wkMain, arma::mat& egamkallMain, arma::colvec& egamkall, arma::colvec& freq_sum, arma::colvec& kall0, double tau2_s0, double tau2_rn, double sigma2_s0, double sigma2_rn, arma::mat& beta_v0i, arma::colvec& beta_v0im0, arma::vec& cpara, Rcpp::List& met_para, arma::colvec& beta, arma::mat& thetaMain, arma::colvec& theta, arma::colvec& xiparMain, double xipar, arma::colvec& gamMain, double gampar, arma::colvec& tau2Main, double tau2, double sigma2, double sigma);
RcppExport SEXP _HBSARSCdev_get_mcmc_2DBSAR_Mono(SEXP ydataSEXP, SEXP vdataSEXP, SEXP vtvSEXP, SEXP iflagMainpnSEXP, SEXP xinxMainSEXP, SEXP xinxSEXP, SEXP xoverMainSEXP, SEXP xoverSEXP, SEXP xdeltaSEXP, SEXP xrangeSEXP, SEXP fxdataSEXP, SEXP fxMaindataSEXP, SEXP fx12dataSEXP, SEXP fx12grid_matSEXP, SEXP fxMain_matSEXP, SEXP f12apx_weightsSEXP, SEXP phixgridSEXP, SEXP phiMainSEXP, SEXP wkSEXP, SEXP wkMainSEXP, SEXP egamkallMainSEXP, SEXP egamkallSEXP, SEXP freq_sumSEXP, SEXP kall0SEXP, SEXP tau2_s0SEXP, SEXP tau2_rnSEXP, SEXP sigma2_s0SEXP, SEXP sigma2_rnSEXP, SEXP beta_v0iSEXP, SEXP beta_v0im0SEXP, SEXP cparaSEXP, SEXP met_paraSEXP, SEXP betaSEXP, SEXP thetaMainSEXP, SEXP thetaSEXP, SEXP xiparMainSEXP, SEXP xiparSEXP, SEXP gamMainSEXP, SEXP gamparSEXP, SEXP tau2MainSEXP, SEXP tau2SEXP, SEXP sigma2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type ydata(ydataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type vdata(vdataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type vtv(vtvSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type iflagMainpn(iflagMainpnSEXP);
    Rcpp::traits::input_parameter< arma::ucube& >::type xinxMain(xinxMainSEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type xinx(xinxSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type xoverMain(xoverMainSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type xover(xoverSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type xdelta(xdeltaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type xrange(xrangeSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type fxdata(fxdataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type fxMaindata(fxMaindataSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type fx12data(fx12dataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type fx12grid_mat(fx12grid_matSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type fxMain_mat(fxMain_matSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type f12apx_weights(f12apx_weightsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phixgrid(phixgridSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type phiMain(phiMainSEXP);
    Rcpp::traits::input_parameter< double >::type wk(wkSEXP);
    Rcpp::traits::input_parameter< double >::type wkMain(wkMainSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type egamkallMain(egamkallMainSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type egamkall(egamkallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type freq_sum(freq_sumSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type kall0(kall0SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_s0(tau2_s0SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_rn(tau2_rnSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_s0(sigma2_s0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_rn(sigma2_rnSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta_v0i(beta_v0iSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type beta_v0im0(beta_v0im0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type cpara(cparaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type met_para(met_paraSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type thetaMain(thetaMainSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type xiparMain(xiparMainSEXP);
    Rcpp::traits::input_parameter< double >::type xipar(xiparSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type gamMain(gamMainSEXP);
    Rcpp::traits::input_parameter< double >::type gampar(gamparSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type tau2Main(tau2MainSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mcmc_2DBSAR_Mono(ydata, vdata, vtv, iflagMainpn, xinxMain, xinx, xoverMain, xover, xdelta, xrange, fxdata, fxMaindata, fx12data, fx12grid_mat, fxMain_mat, f12apx_weights, phixgrid, phiMain, wk, wkMain, egamkallMain, egamkall, freq_sum, kall0, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, met_para, beta, thetaMain, theta, xiparMain, xipar, gamMain, gampar, tau2Main, tau2, sigma2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// get_mcmc_BSAR_Free
Rcpp::List get_mcmc_BSAR_Free(arma::colvec& ydata, arma::mat& vdata, arma::mat& vtv, arma::mat& ptp, arma::colvec& fxdata, arma::mat& phixgrid, arma::mat& phixdata, double wk, arma::colvec& egamkall, arma::colvec& kall, double tau2_s0, double tau2_rn, double sigma2_s0, double sigma2_rn, arma::mat& beta_v0i, arma::colvec& beta_v0im0, arma::vec& cpara, arma::colvec& beta, arma::mat& theta, double gampar, double tau2, double tau, double sigma2, double sigma);
RcppExport SEXP _HBSARSCdev_get_mcmc_BSAR_Free(SEXP ydataSEXP, SEXP vdataSEXP, SEXP vtvSEXP, SEXP ptpSEXP, SEXP fxdataSEXP, SEXP phixgridSEXP, SEXP phixdataSEXP, SEXP wkSEXP, SEXP egamkallSEXP, SEXP kallSEXP, SEXP tau2_s0SEXP, SEXP tau2_rnSEXP, SEXP sigma2_s0SEXP, SEXP sigma2_rnSEXP, SEXP beta_v0iSEXP, SEXP beta_v0im0SEXP, SEXP cparaSEXP, SEXP betaSEXP, SEXP thetaSEXP, SEXP gamparSEXP, SEXP tau2SEXP, SEXP tauSEXP, SEXP sigma2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type ydata(ydataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type vdata(vdataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type vtv(vtvSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ptp(ptpSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type fxdata(fxdataSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phixgrid(phixgridSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phixdata(phixdataSEXP);
    Rcpp::traits::input_parameter< double >::type wk(wkSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type egamkall(egamkallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type kall(kallSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_s0(tau2_s0SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_rn(tau2_rnSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_s0(sigma2_s0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_rn(sigma2_rnSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type beta_v0i(beta_v0iSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type beta_v0im0(beta_v0im0SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type cpara(cparaSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type gampar(gamparSEXP);
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mcmc_BSAR_Free(ydata, vdata, vtv, ptp, fxdata, phixgrid, phixdata, wk, egamkall, kall, tau2_s0, tau2_rn, sigma2_s0, sigma2_rn, beta_v0i, beta_v0im0, cpara, beta, theta, gampar, tau2, tau, sigma2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// get_mcmc_HBBS
Rcpp::List get_mcmc_HBBS(Rcpp::List& data_all, arma::colvec& dpara, arma::colvec& xgrid, arma::umat& xinx, arma::vec& xover, arma::vec& nobs, Rcpp::List& iptHB1, arma::mat& ztz, arma::cube& vtv, arma::cube& wtw, arma::cube& phi2, arma::vec& cpara, Rcpp::List& ace_para, Rcpp::List& probit_para, Rcpp::List& ordinal_para, Rcpp::List& tau_para, Rcpp::List& eta_para, Rcpp::List& met_para, Rcpp::List& squish_para1, Rcpp::List& squish_para2, arma::vec& sigma_para, Rcpp::List& v_para, Rcpp::List& z_para, Rcpp::List& phi_para, Rcpp::List& fx_para, Rcpp::List& basis_para, Rcpp::List& slope_para, arma::colvec& alpha, arma::mat& betall, arma::mat& phi, arma::mat& lambda, arma::mat& lambdai, arma::mat& thetall, arma::colvec& theta0, arma::colvec& xiparall, arma::colvec& tau2all, arma::colvec& tauall, arma::colvec& sigma2, arma::colvec& sigma, arma::cube& betallg, arma::mat& rhoallg, arma::cube& thetallg, arma::cube& zetag, arma::cube& omegag, arma::mat& zeta0g, arma::mat& omega0g, arma::mat& psiallg, arma::colvec& psi0g, arma::mat& mslope_logg, arma::colvec& mslope0_logg, arma::mat& mslopeg, arma::colvec& mslope0g, arma::colvec& mslope_log_sigmag, arma::cube& fxgridallg, arma::mat& f0xgridg);
RcppExport SEXP _HBSARSCdev_get_mcmc_HBBS(SEXP data_allSEXP, SEXP dparaSEXP, SEXP xgridSEXP, SEXP xinxSEXP, SEXP xoverSEXP, SEXP nobsSEXP, SEXP iptHB1SEXP, SEXP ztzSEXP, SEXP vtvSEXP, SEXP wtwSEXP, SEXP phi2SEXP, SEXP cparaSEXP, SEXP ace_paraSEXP, SEXP probit_paraSEXP, SEXP ordinal_paraSEXP, SEXP tau_paraSEXP, SEXP eta_paraSEXP, SEXP met_paraSEXP, SEXP squish_para1SEXP, SEXP squish_para2SEXP, SEXP sigma_paraSEXP, SEXP v_paraSEXP, SEXP z_paraSEXP, SEXP phi_paraSEXP, SEXP fx_paraSEXP, SEXP basis_paraSEXP, SEXP slope_paraSEXP, SEXP alphaSEXP, SEXP betallSEXP, SEXP phiSEXP, SEXP lambdaSEXP, SEXP lambdaiSEXP, SEXP thetallSEXP, SEXP theta0SEXP, SEXP xiparallSEXP, SEXP tau2allSEXP, SEXP tauallSEXP, SEXP sigma2SEXP, SEXP sigmaSEXP, SEXP betallgSEXP, SEXP rhoallgSEXP, SEXP thetallgSEXP, SEXP zetagSEXP, SEXP omegagSEXP, SEXP zeta0gSEXP, SEXP omega0gSEXP, SEXP psiallgSEXP, SEXP psi0gSEXP, SEXP mslope_loggSEXP, SEXP mslope0_loggSEXP, SEXP mslopegSEXP, SEXP mslope0gSEXP, SEXP mslope_log_sigmagSEXP, SEXP fxgridallgSEXP, SEXP f0xgridgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type dpara(dparaSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type xinx(xinxSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type xover(xoverSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type iptHB1(iptHB1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ztz(ztzSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type vtv(vtvSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type wtw(wtwSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type cpara(cparaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type ace_para(ace_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type probit_para(probit_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type ordinal_para(ordinal_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type tau_para(tau_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type eta_para(eta_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type met_para(met_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type squish_para1(squish_para1SEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type squish_para2(squish_para2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sigma_para(sigma_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type v_para(v_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type z_para(z_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type phi_para(phi_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type fx_para(fx_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type basis_para(basis_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type slope_para(slope_paraSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type betall(betallSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type lambdai(lambdaiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type thetall(thetallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type xiparall(xiparallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type tau2all(tau2allSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type tauall(tauallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type betallg(betallgSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type rhoallg(rhoallgSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type thetallg(thetallgSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type zetag(zetagSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type omegag(omegagSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type zeta0g(zeta0gSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type omega0g(omega0gSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type psiallg(psiallgSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type psi0g(psi0gSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mslope_logg(mslope_loggSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type mslope0_logg(mslope0_loggSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mslopeg(mslopegSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type mslope0g(mslope0gSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type mslope_log_sigmag(mslope_log_sigmagSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type fxgridallg(fxgridallgSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type f0xgridg(f0xgridgSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mcmc_HBBS(data_all, dpara, xgrid, xinx, xover, nobs, iptHB1, ztz, vtv, wtw, phi2, cpara, ace_para, probit_para, ordinal_para, tau_para, eta_para, met_para, squish_para1, squish_para2, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, slope_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, xiparall, tau2all, tauall, sigma2, sigma, betallg, rhoallg, thetallg, zetag, omegag, zeta0g, omega0g, psiallg, psi0g, mslope_logg, mslope0_logg, mslopeg, mslope0g, mslope_log_sigmag, fxgridallg, f0xgridg));
    return rcpp_result_gen;
END_RCPP
}
// get_mcmc_2DHBSAR
Rcpp::List get_mcmc_2DHBSAR(Rcpp::List& data_all, arma::vec& nobs, Rcpp::List& iptHB1, arma::mat& ztz, arma::cube& vtv, arma::cube& wtw, arma::cube& phi2, arma::vec& cpara, Rcpp::List& gamma_para, Rcpp::List& tau_para, Rcpp::List& eta_para, Rcpp::List& met_para, arma::vec& sigma_para, Rcpp::List& v_para, Rcpp::List& z_para, Rcpp::List& phi_para, Rcpp::List& fx_para, Rcpp::List& basis_para, arma::colvec& alpha, arma::mat& betall, arma::mat& phi, arma::mat& lambda, arma::mat& lambdai, arma::mat& thetall, arma::colvec& theta0, arma::colvec& gammall, arma::colvec& tau2all, arma::colvec& tauall, arma::colvec& sigma2, arma::colvec& sigma, arma::cube& betallg, arma::cube& thetallg);
RcppExport SEXP _HBSARSCdev_get_mcmc_2DHBSAR(SEXP data_allSEXP, SEXP nobsSEXP, SEXP iptHB1SEXP, SEXP ztzSEXP, SEXP vtvSEXP, SEXP wtwSEXP, SEXP phi2SEXP, SEXP cparaSEXP, SEXP gamma_paraSEXP, SEXP tau_paraSEXP, SEXP eta_paraSEXP, SEXP met_paraSEXP, SEXP sigma_paraSEXP, SEXP v_paraSEXP, SEXP z_paraSEXP, SEXP phi_paraSEXP, SEXP fx_paraSEXP, SEXP basis_paraSEXP, SEXP alphaSEXP, SEXP betallSEXP, SEXP phiSEXP, SEXP lambdaSEXP, SEXP lambdaiSEXP, SEXP thetallSEXP, SEXP theta0SEXP, SEXP gammallSEXP, SEXP tau2allSEXP, SEXP tauallSEXP, SEXP sigma2SEXP, SEXP sigmaSEXP, SEXP betallgSEXP, SEXP thetallgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type iptHB1(iptHB1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ztz(ztzSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type vtv(vtvSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type wtw(wtwSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type cpara(cparaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type gamma_para(gamma_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type tau_para(tau_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type eta_para(eta_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type met_para(met_paraSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sigma_para(sigma_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type v_para(v_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type z_para(z_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type phi_para(phi_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type fx_para(fx_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type basis_para(basis_paraSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type betall(betallSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type lambdai(lambdaiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type thetall(thetallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type gammall(gammallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type tau2all(tau2allSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type tauall(tauallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type betallg(betallgSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type thetallg(thetallgSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mcmc_2DHBSAR(data_all, nobs, iptHB1, ztz, vtv, wtw, phi2, cpara, gamma_para, tau_para, eta_para, met_para, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, gammall, tau2all, tauall, sigma2, sigma, betallg, thetallg));
    return rcpp_result_gen;
END_RCPP
}
// get_mcmc_HBSAR
Rcpp::List get_mcmc_HBSAR(Rcpp::List& data_all, arma::colvec& dpara, arma::colvec& xgrid, arma::umat& xinx, arma::vec& xover, arma::vec& nobs, Rcpp::List& iptHB1, arma::mat& ztz, arma::cube& vtv, arma::cube& wtw, arma::cube& phi2, arma::vec& cpara, Rcpp::List& ace_para, Rcpp::List& probit_para, Rcpp::List& ordinal_para, Rcpp::List& gamma_para, Rcpp::List& tau_para, Rcpp::List& eta_para, Rcpp::List& met_para, Rcpp::List& squish_para1, Rcpp::List& squish_para2, arma::vec& sigma_para, Rcpp::List& v_para, Rcpp::List& z_para, Rcpp::List& phi_para, Rcpp::List& fx_para, Rcpp::List& basis_para, Rcpp::List& slope_para, arma::colvec& alpha, arma::mat& betall, arma::mat& phi, arma::mat& lambda, arma::mat& lambdai, arma::mat& thetall, arma::colvec& theta0, arma::colvec& xiparall, arma::colvec& gammall, arma::colvec& tau2all, arma::colvec& tauall, arma::colvec& sigma2, arma::colvec& sigma, arma::cube& betallg, arma::mat& rhoallg, arma::cube& thetallg, arma::cube& zetag, arma::cube& omegag, arma::mat& zeta0g, arma::mat& omega0g, arma::mat& psiallg, arma::colvec& psi0g, arma::mat& mslope_logg, arma::colvec& mslope0_logg, arma::mat& mslopeg, arma::colvec& mslope0g, arma::colvec& mslope_log_sigmag, arma::cube& fxgridallg, arma::mat& f0xgridg);
RcppExport SEXP _HBSARSCdev_get_mcmc_HBSAR(SEXP data_allSEXP, SEXP dparaSEXP, SEXP xgridSEXP, SEXP xinxSEXP, SEXP xoverSEXP, SEXP nobsSEXP, SEXP iptHB1SEXP, SEXP ztzSEXP, SEXP vtvSEXP, SEXP wtwSEXP, SEXP phi2SEXP, SEXP cparaSEXP, SEXP ace_paraSEXP, SEXP probit_paraSEXP, SEXP ordinal_paraSEXP, SEXP gamma_paraSEXP, SEXP tau_paraSEXP, SEXP eta_paraSEXP, SEXP met_paraSEXP, SEXP squish_para1SEXP, SEXP squish_para2SEXP, SEXP sigma_paraSEXP, SEXP v_paraSEXP, SEXP z_paraSEXP, SEXP phi_paraSEXP, SEXP fx_paraSEXP, SEXP basis_paraSEXP, SEXP slope_paraSEXP, SEXP alphaSEXP, SEXP betallSEXP, SEXP phiSEXP, SEXP lambdaSEXP, SEXP lambdaiSEXP, SEXP thetallSEXP, SEXP theta0SEXP, SEXP xiparallSEXP, SEXP gammallSEXP, SEXP tau2allSEXP, SEXP tauallSEXP, SEXP sigma2SEXP, SEXP sigmaSEXP, SEXP betallgSEXP, SEXP rhoallgSEXP, SEXP thetallgSEXP, SEXP zetagSEXP, SEXP omegagSEXP, SEXP zeta0gSEXP, SEXP omega0gSEXP, SEXP psiallgSEXP, SEXP psi0gSEXP, SEXP mslope_loggSEXP, SEXP mslope0_loggSEXP, SEXP mslopegSEXP, SEXP mslope0gSEXP, SEXP mslope_log_sigmagSEXP, SEXP fxgridallgSEXP, SEXP f0xgridgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List& >::type data_all(data_allSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type dpara(dparaSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< arma::umat& >::type xinx(xinxSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type xover(xoverSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type iptHB1(iptHB1SEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ztz(ztzSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type vtv(vtvSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type wtw(wtwSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type phi2(phi2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type cpara(cparaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type ace_para(ace_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type probit_para(probit_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type ordinal_para(ordinal_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type gamma_para(gamma_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type tau_para(tau_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type eta_para(eta_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type met_para(met_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type squish_para1(squish_para1SEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type squish_para2(squish_para2SEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type sigma_para(sigma_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type v_para(v_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type z_para(z_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type phi_para(phi_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type fx_para(fx_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type basis_para(basis_paraSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type slope_para(slope_paraSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type betall(betallSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type lambdai(lambdaiSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type thetall(thetallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type xiparall(xiparallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type gammall(gammallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type tau2all(tau2allSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type tauall(tauallSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type betallg(betallgSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type rhoallg(rhoallgSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type thetallg(thetallgSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type zetag(zetagSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type omegag(omegagSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type zeta0g(zeta0gSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type omega0g(omega0gSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type psiallg(psiallgSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type psi0g(psi0gSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mslope_logg(mslope_loggSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type mslope0_logg(mslope0_loggSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type mslopeg(mslopegSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type mslope0g(mslope0gSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type mslope_log_sigmag(mslope_log_sigmagSEXP);
    Rcpp::traits::input_parameter< arma::cube& >::type fxgridallg(fxgridallgSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type f0xgridg(f0xgridgSEXP);
    rcpp_result_gen = Rcpp::wrap(get_mcmc_HBSAR(data_all, dpara, xgrid, xinx, xover, nobs, iptHB1, ztz, vtv, wtw, phi2, cpara, ace_para, probit_para, ordinal_para, gamma_para, tau_para, eta_para, met_para, squish_para1, squish_para2, sigma_para, v_para, z_para, phi_para, fx_para, basis_para, slope_para, alpha, betall, phi, lambda, lambdai, thetall, theta0, xiparall, gammall, tau2all, tauall, sigma2, sigma, betallg, rhoallg, thetallg, zetag, omegag, zeta0g, omega0g, psiallg, psi0g, mslope_logg, mslope0_logg, mslopeg, mslope0g, mslope_log_sigmag, fxgridallg, f0xgridg));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_CumTrap
arma::colvec rcpp_CumTrap(arma::colvec f, double delta);
RcppExport SEXP _HBSARSCdev_rcpp_CumTrap(SEXP fSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_CumTrap(f, delta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_trapint
double rcpp_trapint(arma::colvec f, double xdelta);
RcppExport SEXP _HBSARSCdev_rcpp_trapint(SEXP fSEXP, SEXP xdeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type xdelta(xdeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_trapint(f, xdelta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Int2D
double rcpp_Int2D(arma::mat fmat, arma::colvec xdelta);
RcppExport SEXP _HBSARSCdev_rcpp_Int2D(SEXP fmatSEXP, SEXP xdeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type fmat(fmatSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type xdelta(xdeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Int2D(fmat, xdelta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_CumInt2D
arma::mat rcpp_CumInt2D(arma::mat fmat, arma::colvec xdelta);
RcppExport SEXP _HBSARSCdev_rcpp_CumInt2D(SEXP fmatSEXP, SEXP xdeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type fmat(fmatSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type xdelta(xdeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_CumInt2D(fmat, xdelta));
    return rcpp_result_gen;
END_RCPP
}
// get_ex_idx
arma::uvec get_ex_idx(unsigned int len, arma::uvec idx);
RcppExport SEXP _HBSARSCdev_get_ex_idx(SEXP lenSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type len(lenSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ex_idx(len, idx));
    return rcpp_result_gen;
END_RCPP
}
// get_seq
arma::uvec get_seq(unsigned int a, unsigned int b);
RcppExport SEXP _HBSARSCdev_get_seq(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type a(aSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(get_seq(a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rndtna
double rcpp_rndtna(double mu, double sigma, double xtop);
RcppExport SEXP _HBSARSCdev_rcpp_rndtna(SEXP muSEXP, SEXP sigmaSEXP, SEXP xtopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xtop(xtopSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_rndtna(mu, sigma, xtop));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rndtna2
arma::colvec rcpp_rndtna2(arma::colvec mu, double sigma, double xtop);
RcppExport SEXP _HBSARSCdev_rcpp_rndtna2(SEXP muSEXP, SEXP sigmaSEXP, SEXP xtopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xtop(xtopSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_rndtna2(mu, sigma, xtop));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rndtnb
double rcpp_rndtnb(double mu, double sigma, double xbot);
RcppExport SEXP _HBSARSCdev_rcpp_rndtnb(SEXP muSEXP, SEXP sigmaSEXP, SEXP xbotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xbot(xbotSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_rndtnb(mu, sigma, xbot));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rndtnb2
arma::colvec rcpp_rndtnb2(arma::colvec mu, double sigma, double xbot);
RcppExport SEXP _HBSARSCdev_rcpp_rndtnb2(SEXP muSEXP, SEXP sigmaSEXP, SEXP xbotSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xbot(xbotSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_rndtnb2(mu, sigma, xbot));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_rndtnab
double rcpp_rndtnab(double mu, double sigma, double xbot, double xtop);
RcppExport SEXP _HBSARSCdev_rcpp_rndtnab(SEXP muSEXP, SEXP sigmaSEXP, SEXP xbotSEXP, SEXP xtopSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xbot(xbotSEXP);
    Rcpp::traits::input_parameter< double >::type xtop(xtopSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_rndtnab(mu, sigma, xbot, xtop));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_GetSquish
arma::colvec rcpp_GetSquish(arma::colvec omega, double psi, arma::colvec xgrid);
RcppExport SEXP _HBSARSCdev_rcpp_GetSquish(SEXP omegaSEXP, SEXP psiSEXP, SEXP xgridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type xgrid(xgridSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_GetSquish(omega, psi, xgrid));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_GetMonofxgrid
arma::colvec rcpp_GetMonofxgrid(Rcpp::List fpars);
RcppExport SEXP _HBSARSCdev_rcpp_GetMonofxgrid(SEXP fparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fpars(fparsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_GetMonofxgrid(fpars));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_GetMonoSamefxgrid
arma::colvec rcpp_GetMonoSamefxgrid(Rcpp::List fpars);
RcppExport SEXP _HBSARSCdev_rcpp_GetMonoSamefxgrid(SEXP fparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fpars(fparsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_GetMonoSamefxgrid(fpars));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_GetMonoDiffxgrid
arma::colvec rcpp_GetMonoDiffxgrid(Rcpp::List fpars);
RcppExport SEXP _HBSARSCdev_rcpp_GetMonoDiffxgrid(SEXP fparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fpars(fparsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_GetMonoDiffxgrid(fpars));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_GetSfxgrid
arma::colvec rcpp_GetSfxgrid(Rcpp::List fpars, int d3);
RcppExport SEXP _HBSARSCdev_rcpp_GetSfxgrid(SEXP fparsSEXP, SEXP d3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fpars(fparsSEXP);
    Rcpp::traits::input_parameter< int >::type d3(d3SEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_GetSfxgrid(fpars, d3));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_GetUseg
arma::colvec rcpp_GetUseg(arma::colvec x, arma::colvec gz, double omega, double xdelta);
RcppExport SEXP _HBSARSCdev_rcpp_GetUseg(SEXP xSEXP, SEXP gzSEXP, SEXP omegaSEXP, SEXP xdeltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type gz(gzSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type xdelta(xdeltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_GetUseg(x, gz, omega, xdelta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_GetMMfxgrid
arma::colvec rcpp_GetMMfxgrid(Rcpp::List fpars);
RcppExport SEXP _HBSARSCdev_rcpp_GetMMfxgrid(SEXP fparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fpars(fparsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_GetMMfxgrid(fpars));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_GetUfxgrid
arma::colvec rcpp_GetUfxgrid(Rcpp::List fpars);
RcppExport SEXP _HBSARSCdev_rcpp_GetUfxgrid(SEXP fparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fpars(fparsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_GetUfxgrid(fpars));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_Getfx
arma::colvec rcpp_Getfx(Rcpp::List fpars);
RcppExport SEXP _HBSARSCdev_rcpp_Getfx(SEXP fparsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type fpars(fparsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_Getfx(fpars));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_GetSCfxobs
arma::colvec rcpp_GetSCfxobs(arma::umat& xinx, arma::vec& xover, arma::colvec& fxgrid);
RcppExport SEXP _HBSARSCdev_rcpp_GetSCfxobs(SEXP xinxSEXP, SEXP xoverSEXP, SEXP fxgridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::umat& >::type xinx(xinxSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type xover(xoverSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type fxgrid(fxgridSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_GetSCfxobs(xinx, xover, fxgrid));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cholSol
arma::colvec rcpp_cholSol(arma::colvec& b, arma::mat& U);
RcppExport SEXP _HBSARSCdev_rcpp_cholSol(SEXP bSEXP, SEXP USEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type U(USEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cholSol(b, U));
    return rcpp_result_gen;
END_RCPP
}
// GetMetVec
arma::colvec GetMetVec(double w, double m0, double alpha, unsigned int ndim);
RcppExport SEXP _HBSARSCdev_GetMetVec(SEXP wSEXP, SEXP m0SEXP, SEXP alphaSEXP, SEXP ndimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ndim(ndimSEXP);
    rcpp_result_gen = Rcpp::wrap(GetMetVec(w, m0, alpha, ndim));
    return rcpp_result_gen;
END_RCPP
}
// SetMetVec
void SetMetVec(arma::colvec& Met, double w, double m0, double alpha, unsigned int ndim);
RcppExport SEXP _HBSARSCdev_SetMetVec(SEXP MetSEXP, SEXP wSEXP, SEXP m0SEXP, SEXP alphaSEXP, SEXP ndimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type Met(MetSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type m0(m0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ndim(ndimSEXP);
    SetMetVec(Met, w, m0, alpha, ndim);
    return R_NilValue;
END_RCPP
}
// AdaptMetVar
arma::colvec AdaptMetVar(arma::colvec x);
RcppExport SEXP _HBSARSCdev_AdaptMetVar(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(AdaptMetVar(x));
    return rcpp_result_gen;
END_RCPP
}
// AdaptMetUpdate
void AdaptMetUpdate(arma::colvec& x);
RcppExport SEXP _HBSARSCdev_AdaptMetUpdate(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type x(xSEXP);
    AdaptMetUpdate(x);
    return R_NilValue;
END_RCPP
}
// AdaptMetUpdate2
arma::colvec AdaptMetUpdate2(arma::colvec x);
RcppExport SEXP _HBSARSCdev_AdaptMetUpdate2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(AdaptMetUpdate2(x));
    return rcpp_result_gen;
END_RCPP
}
// UpdateMet
void UpdateMet(arma::colvec& x, unsigned int nb, double fct);
RcppExport SEXP _HBSARSCdev_UpdateMet(SEXP xSEXP, SEXP nbSEXP, SEXP fctSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type fct(fctSEXP);
    UpdateMet(x, nb, fct);
    return R_NilValue;
END_RCPP
}
// UpdateMet2
arma::colvec UpdateMet2(arma::colvec x, unsigned int nb, double fct);
RcppExport SEXP _HBSARSCdev_UpdateMet2(SEXP xSEXP, SEXP nbSEXP, SEXP fctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nb(nbSEXP);
    Rcpp::traits::input_parameter< double >::type fct(fctSEXP);
    rcpp_result_gen = Rcpp::wrap(UpdateMet2(x, nb, fct));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_getsmooth
arma::colvec rcpp_getsmooth(double tau2, double gampar, arma::colvec& egamkall, arma::colvec theta2, double wk, double tau2_s0, double tau2_rn, arma::colvec freq_sum);
RcppExport SEXP _HBSARSCdev_rcpp_getsmooth(SEXP tau2SEXP, SEXP gamparSEXP, SEXP egamkallSEXP, SEXP theta2SEXP, SEXP wkSEXP, SEXP tau2_s0SEXP, SEXP tau2_rnSEXP, SEXP freq_sumSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type gampar(gamparSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type egamkall(egamkallSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< double >::type wk(wkSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_s0(tau2_s0SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_rn(tau2_rnSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type freq_sum(freq_sumSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_getsmooth(tau2, gampar, egamkall, theta2, wk, tau2_s0, tau2_rn, freq_sum));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_getsmoothSC
Rcpp::List rcpp_getsmoothSC(double tau2, double gampar, arma::colvec theta, arma::colvec theta2, arma::colvec freqs, arma::colvec egamkall, double wk, double tau2_s0, double tau2_rn, bool bflagZ);
RcppExport SEXP _HBSARSCdev_rcpp_getsmoothSC(SEXP tau2SEXP, SEXP gamparSEXP, SEXP thetaSEXP, SEXP theta2SEXP, SEXP freqsSEXP, SEXP egamkallSEXP, SEXP wkSEXP, SEXP tau2_s0SEXP, SEXP tau2_rnSEXP, SEXP bflagZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type gampar(gamparSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type theta2(theta2SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type freqs(freqsSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type egamkall(egamkallSEXP);
    Rcpp::traits::input_parameter< double >::type wk(wkSEXP);
    Rcpp::traits::input_parameter< double >::type tau2_s0(tau2_s0SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_rn(tau2_rnSEXP);
    Rcpp::traits::input_parameter< bool >::type bflagZ(bflagZSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_getsmoothSC(tau2, gampar, theta, theta2, freqs, egamkall, wk, tau2_s0, tau2_rn, bflagZ));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fdata_apx
arma::colvec rcpp_fdata_apx(arma::mat fmat, arma::mat f12apx_weights, arma::umat xinx, arma::mat xover, unsigned int nint);
RcppExport SEXP _HBSARSCdev_rcpp_fdata_apx(SEXP fmatSEXP, SEXP f12apx_weightsSEXP, SEXP xinxSEXP, SEXP xoverSEXP, SEXP nintSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type fmat(fmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type f12apx_weights(f12apx_weightsSEXP);
    Rcpp::traits::input_parameter< arma::umat >::type xinx(xinxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xover(xoverSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nint(nintSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fdata_apx(fmat, f12apx_weights, xinx, xover, nint));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_phixgrid_2D
void rcpp_get_phixgrid_2D(arma::mat& phixgrid, arma::mat& xgrid, arma::colvec& xrange, arma::colvec& xmin, arma::mat& freq_all, double phix0, double phiy0, unsigned int ntheta, unsigned int nint);
RcppExport SEXP _HBSARSCdev_rcpp_get_phixgrid_2D(SEXP phixgridSEXP, SEXP xgridSEXP, SEXP xrangeSEXP, SEXP xminSEXP, SEXP freq_allSEXP, SEXP phix0SEXP, SEXP phiy0SEXP, SEXP nthetaSEXP, SEXP nintSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type phixgrid(phixgridSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type xrange(xrangeSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type freq_all(freq_allSEXP);
    Rcpp::traits::input_parameter< double >::type phix0(phix0SEXP);
    Rcpp::traits::input_parameter< double >::type phiy0(phiy0SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ntheta(nthetaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nint(nintSEXP);
    rcpp_get_phixgrid_2D(phixgrid, xgrid, xrange, xmin, freq_all, phix0, phiy0, ntheta, nint);
    return R_NilValue;
END_RCPP
}
// GetSmoothGamma
double GetSmoothGamma(double gampar, arma::colvec theta, arma::colvec theta0, arma::colvec tau2, double gamma_alpha, double gamma_beta, double wk, arma::colvec kall, double gmax);
RcppExport SEXP _HBSARSCdev_GetSmoothGamma(SEXP gamparSEXP, SEXP thetaSEXP, SEXP theta0SEXP, SEXP tau2SEXP, SEXP gamma_alphaSEXP, SEXP gamma_betaSEXP, SEXP wkSEXP, SEXP kallSEXP, SEXP gmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type gampar(gamparSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type gamma_alpha(gamma_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_beta(gamma_betaSEXP);
    Rcpp::traits::input_parameter< double >::type wk(wkSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type kall(kallSEXP);
    Rcpp::traits::input_parameter< double >::type gmax(gmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(GetSmoothGamma(gampar, theta, theta0, tau2, gamma_alpha, gamma_beta, wk, kall, gmax));
    return rcpp_result_gen;
END_RCPP
}
// GetGammaHyper
Rcpp::List GetGammaHyper(double gamma_alpha, double gamma_beta, double gamma_mu, double gamma_sigma, double gamma_sigma2, arma::colvec gammall, arma::colvec theta0, double eta02, double gamma_sum, double lgamma_sum, arma::colvec kall, arma::colvec gamma_met, double mu_bot, double mu_top, double sigma_bot, double sigma_top, double gamma_mu_m0, double gamma_mu_v02, double gamma_sigma_m0, double gamma_sigma_v02, int ingroup, arma::colvec freq_sum, double gmax);
RcppExport SEXP _HBSARSCdev_GetGammaHyper(SEXP gamma_alphaSEXP, SEXP gamma_betaSEXP, SEXP gamma_muSEXP, SEXP gamma_sigmaSEXP, SEXP gamma_sigma2SEXP, SEXP gammallSEXP, SEXP theta0SEXP, SEXP eta02SEXP, SEXP gamma_sumSEXP, SEXP lgamma_sumSEXP, SEXP kallSEXP, SEXP gamma_metSEXP, SEXP mu_botSEXP, SEXP mu_topSEXP, SEXP sigma_botSEXP, SEXP sigma_topSEXP, SEXP gamma_mu_m0SEXP, SEXP gamma_mu_v02SEXP, SEXP gamma_sigma_m0SEXP, SEXP gamma_sigma_v02SEXP, SEXP ingroupSEXP, SEXP freq_sumSEXP, SEXP gmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type gamma_alpha(gamma_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_beta(gamma_betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_mu(gamma_muSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_sigma(gamma_sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_sigma2(gamma_sigma2SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type gammall(gammallSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< double >::type eta02(eta02SEXP);
    Rcpp::traits::input_parameter< double >::type gamma_sum(gamma_sumSEXP);
    Rcpp::traits::input_parameter< double >::type lgamma_sum(lgamma_sumSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type kall(kallSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type gamma_met(gamma_metSEXP);
    Rcpp::traits::input_parameter< double >::type mu_bot(mu_botSEXP);
    Rcpp::traits::input_parameter< double >::type mu_top(mu_topSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_bot(sigma_botSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_top(sigma_topSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_mu_m0(gamma_mu_m0SEXP);
    Rcpp::traits::input_parameter< double >::type gamma_mu_v02(gamma_mu_v02SEXP);
    Rcpp::traits::input_parameter< double >::type gamma_sigma_m0(gamma_sigma_m0SEXP);
    Rcpp::traits::input_parameter< double >::type gamma_sigma_v02(gamma_sigma_v02SEXP);
    Rcpp::traits::input_parameter< int >::type ingroup(ingroupSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type freq_sum(freq_sumSEXP);
    Rcpp::traits::input_parameter< double >::type gmax(gmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(GetGammaHyper(gamma_alpha, gamma_beta, gamma_mu, gamma_sigma, gamma_sigma2, gammall, theta0, eta02, gamma_sum, lgamma_sum, kall, gamma_met, mu_bot, mu_top, sigma_bot, sigma_top, gamma_mu_m0, gamma_mu_v02, gamma_sigma_m0, gamma_sigma_v02, ingroup, freq_sum, gmax));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_GetMainfxdata
arma::colvec rcpp_GetMainfxdata(arma::uvec xinx, arma::colvec xover, arma::colvec fxgrid);
RcppExport SEXP _HBSARSCdev_rcpp_GetMainfxdata(SEXP xinxSEXP, SEXP xoverSEXP, SEXP fxgridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type xinx(xinxSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type xover(xoverSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type fxgrid(fxgridSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_GetMainfxdata(xinx, xover, fxgrid));
    return rcpp_result_gen;
END_RCPP
}
// get_phixgrid2D
arma::mat get_phixgrid2D(arma::mat xgrid, double phix0, double phiy0, arma::mat freq_all, arma::vec xmin, arma::vec xrange, unsigned int ntheta, unsigned int nint);
RcppExport SEXP _HBSARSCdev_get_phixgrid2D(SEXP xgridSEXP, SEXP phix0SEXP, SEXP phiy0SEXP, SEXP freq_allSEXP, SEXP xminSEXP, SEXP xrangeSEXP, SEXP nthetaSEXP, SEXP nintSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type xgrid(xgridSEXP);
    Rcpp::traits::input_parameter< double >::type phix0(phix0SEXP);
    Rcpp::traits::input_parameter< double >::type phiy0(phiy0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type freq_all(freq_allSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type xrange(xrangeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type ntheta(nthetaSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type nint(nintSEXP);
    rcpp_result_gen = Rcpp::wrap(get_phixgrid2D(xgrid, phix0, phiy0, freq_all, xmin, xrange, ntheta, nint));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HBSARSCdev_get_mcmc_BBS_Free", (DL_FUNC) &_HBSARSCdev_get_mcmc_BBS_Free, 21},
    {"_HBSARSCdev_get_mcmc_2DBSAR_Free", (DL_FUNC) &_HBSARSCdev_get_mcmc_2DBSAR_Free, 24},
    {"_HBSARSCdev_get_mcmc_2DBSAR_Mono", (DL_FUNC) &_HBSARSCdev_get_mcmc_2DBSAR_Mono, 43},
    {"_HBSARSCdev_get_mcmc_BSAR_Free", (DL_FUNC) &_HBSARSCdev_get_mcmc_BSAR_Free, 24},
    {"_HBSARSCdev_get_mcmc_HBBS", (DL_FUNC) &_HBSARSCdev_get_mcmc_HBBS, 55},
    {"_HBSARSCdev_get_mcmc_2DHBSAR", (DL_FUNC) &_HBSARSCdev_get_mcmc_2DHBSAR, 32},
    {"_HBSARSCdev_get_mcmc_HBSAR", (DL_FUNC) &_HBSARSCdev_get_mcmc_HBSAR, 57},
    {"_HBSARSCdev_rcpp_CumTrap", (DL_FUNC) &_HBSARSCdev_rcpp_CumTrap, 2},
    {"_HBSARSCdev_rcpp_trapint", (DL_FUNC) &_HBSARSCdev_rcpp_trapint, 2},
    {"_HBSARSCdev_rcpp_Int2D", (DL_FUNC) &_HBSARSCdev_rcpp_Int2D, 2},
    {"_HBSARSCdev_rcpp_CumInt2D", (DL_FUNC) &_HBSARSCdev_rcpp_CumInt2D, 2},
    {"_HBSARSCdev_get_ex_idx", (DL_FUNC) &_HBSARSCdev_get_ex_idx, 2},
    {"_HBSARSCdev_get_seq", (DL_FUNC) &_HBSARSCdev_get_seq, 2},
    {"_HBSARSCdev_rcpp_rndtna", (DL_FUNC) &_HBSARSCdev_rcpp_rndtna, 3},
    {"_HBSARSCdev_rcpp_rndtna2", (DL_FUNC) &_HBSARSCdev_rcpp_rndtna2, 3},
    {"_HBSARSCdev_rcpp_rndtnb", (DL_FUNC) &_HBSARSCdev_rcpp_rndtnb, 3},
    {"_HBSARSCdev_rcpp_rndtnb2", (DL_FUNC) &_HBSARSCdev_rcpp_rndtnb2, 3},
    {"_HBSARSCdev_rcpp_rndtnab", (DL_FUNC) &_HBSARSCdev_rcpp_rndtnab, 4},
    {"_HBSARSCdev_rcpp_GetSquish", (DL_FUNC) &_HBSARSCdev_rcpp_GetSquish, 3},
    {"_HBSARSCdev_rcpp_GetMonofxgrid", (DL_FUNC) &_HBSARSCdev_rcpp_GetMonofxgrid, 1},
    {"_HBSARSCdev_rcpp_GetMonoSamefxgrid", (DL_FUNC) &_HBSARSCdev_rcpp_GetMonoSamefxgrid, 1},
    {"_HBSARSCdev_rcpp_GetMonoDiffxgrid", (DL_FUNC) &_HBSARSCdev_rcpp_GetMonoDiffxgrid, 1},
    {"_HBSARSCdev_rcpp_GetSfxgrid", (DL_FUNC) &_HBSARSCdev_rcpp_GetSfxgrid, 2},
    {"_HBSARSCdev_rcpp_GetUseg", (DL_FUNC) &_HBSARSCdev_rcpp_GetUseg, 4},
    {"_HBSARSCdev_rcpp_GetMMfxgrid", (DL_FUNC) &_HBSARSCdev_rcpp_GetMMfxgrid, 1},
    {"_HBSARSCdev_rcpp_GetUfxgrid", (DL_FUNC) &_HBSARSCdev_rcpp_GetUfxgrid, 1},
    {"_HBSARSCdev_rcpp_Getfx", (DL_FUNC) &_HBSARSCdev_rcpp_Getfx, 1},
    {"_HBSARSCdev_rcpp_GetSCfxobs", (DL_FUNC) &_HBSARSCdev_rcpp_GetSCfxobs, 3},
    {"_HBSARSCdev_rcpp_cholSol", (DL_FUNC) &_HBSARSCdev_rcpp_cholSol, 2},
    {"_HBSARSCdev_GetMetVec", (DL_FUNC) &_HBSARSCdev_GetMetVec, 4},
    {"_HBSARSCdev_SetMetVec", (DL_FUNC) &_HBSARSCdev_SetMetVec, 5},
    {"_HBSARSCdev_AdaptMetVar", (DL_FUNC) &_HBSARSCdev_AdaptMetVar, 1},
    {"_HBSARSCdev_AdaptMetUpdate", (DL_FUNC) &_HBSARSCdev_AdaptMetUpdate, 1},
    {"_HBSARSCdev_AdaptMetUpdate2", (DL_FUNC) &_HBSARSCdev_AdaptMetUpdate2, 1},
    {"_HBSARSCdev_UpdateMet", (DL_FUNC) &_HBSARSCdev_UpdateMet, 3},
    {"_HBSARSCdev_UpdateMet2", (DL_FUNC) &_HBSARSCdev_UpdateMet2, 3},
    {"_HBSARSCdev_rcpp_getsmooth", (DL_FUNC) &_HBSARSCdev_rcpp_getsmooth, 8},
    {"_HBSARSCdev_rcpp_getsmoothSC", (DL_FUNC) &_HBSARSCdev_rcpp_getsmoothSC, 10},
    {"_HBSARSCdev_rcpp_fdata_apx", (DL_FUNC) &_HBSARSCdev_rcpp_fdata_apx, 5},
    {"_HBSARSCdev_rcpp_get_phixgrid_2D", (DL_FUNC) &_HBSARSCdev_rcpp_get_phixgrid_2D, 9},
    {"_HBSARSCdev_GetSmoothGamma", (DL_FUNC) &_HBSARSCdev_GetSmoothGamma, 9},
    {"_HBSARSCdev_GetGammaHyper", (DL_FUNC) &_HBSARSCdev_GetGammaHyper, 23},
    {"_HBSARSCdev_rcpp_GetMainfxdata", (DL_FUNC) &_HBSARSCdev_rcpp_GetMainfxdata, 3},
    {"_HBSARSCdev_get_phixgrid2D", (DL_FUNC) &_HBSARSCdev_get_phixgrid2D, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_HBSARSCdev(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
